version: '3.9'

services:
  bashapi:
    container_name: golang_container
    environment:
      - CONFIG_PATH=/root/config/config.yml
      - GIN_MODE=release
    tty: true
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - learning

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=bashapiadmin
      - POSTGRES_PASSWORD=bashAPIdb
      - POSTGRES_DB=bashapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - learning

  migrate:
    image: migrate/migrate
    container_name: migrate_container
    networks:
      - learning
    volumes:
      - ./migrations:/root/migrations
    command: ["-path", "/root/migrations", "-database", "postgres://bashapiadmin:bashAPIdb@db:5432/bashapidb?sslmode=disable", "up"]
    depends_on:
      - db



networks:
  learning:
    driver: bridge

volumes:
  postgres_data:
