version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: bashapidb
      POSTGRES_USER: bashapiadmin
      POSTGRES_PASSWORD: bashAPIdb
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
