env: prod
server:
  host: 0.0.0.0
  port: 8000
  read_timeout: 10 # seconds
  write_timeout: 10 # seconds
postgres:
  host: db
  port: 5432
  user: bashapiadmin
  database: bashapidb
  password: bashAPIdb
  ssl_mode: disable
commands:
  max_concurrent: 100
  timeout: 200 # seconds