env: local
server:
  host: 0.0.0.0
  port: 8000
  read_timeout: 10 # seconds
  write_timeout: 10 # seconds
postgres:
  host: localhost
  port: 5432
  user: bashapiadmin
  database: bashapidb
  password: bashAPIdb
  ssl_mode: disable
commands:
  max_concurrent: 2
  timeout: 11 # seconds