name: Go CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Compose up
      run: |
        docker-compose up -d

    - name: Docker Compose Build
      run: |
        docker-compose build

    - name: Docker Compose Run
      run: |
        docker-compose run bashapi

    - name: Docker Compose Push (only main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker-compose push

    - name: Clean up
      run: |
        docker-compose down

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

